# This file is for use with Docker!
# This is a compose file for development! Do not use in prod!

services:
  jhaas-portal-backend:
    image: jhaas-portal-backend
    container_name: jhaas-portal-backend
    hostname: jhaas-portal-backend
    restart: unless-stopped
    build:
      context: .
      target: develop
    depends_on:
      - jhaas-portal-db
      - redis
      - mailhog
      - minio
      - authentik
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./environments/app.env
      - ./environments/db.env
    volumes:
      - cache:${CACHEDIR:-/jhaas-cache}
      - ./:${APPDIR:-/jhaas-app}
      - ./docker-entrypoint-dev.sh:/entrypoint.sh

  jhaas-portal-db:
    image: postgres:15
    container_name: jhaas-portal-db
    hostname: jhaas-portal-db
    restart: unless-stopped
    networks:
      - jhaas-portal-priv
    env_file:
      - ./environments/db.env
    volumes:
      - './environments/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh'
      - 'postgres-data:/var/lib/postgresql/data'

  minio:
    image: quay.io/minio/minio
    container_name: jhaas-minio
    hostname: jhaas-minio
    restart: unless-stopped
    networks:
      - jhaas-portal-priv
    volumes:
      - 'minio-data:/data'
    env_file:
      - ./environments/minio.env
    command: server --console-address ":9001" /data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    hostname: mailhog
    restart: unless-stopped
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:2525
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - 'mailhog-data:/maildir'
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:8025:8025
    expose:
      - 2525

  redis:
    image: redis:alpine
    container_name: jhaas-redis
    hostname: jhaas-redis
    restart: unless-stopped
    networks:
      - jhaas-portal-priv
    volumes:
      - redis-data:/data

  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2023.6.1}
    container_name: jhaas-authentik
    hostname: jhaas-authentik
    restart: unless-stopped
    command: server
    depends_on:
      - jhaas-portal-db
      - redis
    networks:
      - jhaas-portal-priv
    env_file:
      - ./environments/authentik.env
      - ./environments/db.env
    volumes:
      - './environments/authentik_blueprints:/blueprints:ro'
      - './environments/authentik_templates:/templates:ro'
      - './environments/authentik_flow_backgrounds:/web/dist/assets/images/backgrounds:ro'
    ports:
      - 127.0.0.1:9000:9000

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2023.6.1}
    container_name: jhaas-authentik-worker
    hostname: jhaas-authentik-worker
    restart: unless-stopped
    command: worker
    networks:
      - jhaas-portal-priv
    depends_on:
      - jhaas-portal-db
      - redis
    user: root
    env_file:
      - ./environments/authentik.env
      - ./environments/db.env
    volumes:
      - './environments/authentik_blueprints:/blueprints:ro'
      - './environments/authentik_templates:/templates:ro'

networks:
  jhaas-portal-priv:
    external: false
    name: jhaas-portal-priv

volumes:
  cache:
    name: jhaas-portal-cache
  mailhog-data:
    name: jhaas-mailhog-data
  minio-data:
    name: jhaas-minio-data
  postgres-data:
    name: jhaas-postgres-data
  redis-data:
    name: jhaas-redis-data
