# This is a compose file for development! Do not use in prod!
version: '3'

services:
  jhaas-portal-backend:
    image: jhaas-portal-backend
    container_name: jhaas-portal-backend
    hostname: jhaas-portal-backend
    build:
      context: .
      target: develop
    depends_on:
      - jhaas-portal-db
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./environments/app.env
      - ./environments/db.env
    volumes:
      - cache:${CACHEDIR:-/jhaas-cache}
      - ./:${APPDIR:-/jhaas-app}

  jhaas-portal-db:
    image: postgres:15
    container_name: jhaas-portal-db
    hostname: jhaas-portal-db
    networks:
      - jhaas-portal-priv
    env_file:
      - ./environments/db.env

  minio:
    image: quay.io/minio/minio
    container_name: jhaas-minio
    hostname: jhaas-minio
    restart: unless-stopped
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:9001:9001
    volumes:
      - 'minio-data:/data'
    env_file:
      - ./environments/minio.env
    command: server --console-address ":9001" /data

networks:
  jhaas-portal-priv:
    external: false
    name: jhaas-portal-priv

volumes:
  cache:
    name: jhaas-portal-cache
  minio-data:
    name: jhaas-minio-data
