version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    hostname: keycloak
    restart: unless-stopped
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=password
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:8080:8080
    command: start-dev

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    hostname: keycloak-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - jhaas-portal-priv
    volumes:
      - 'keycloak-db-data:/var/lib/postgresql/data'

volumes:
  keycloak-db-data:

networks:
  jhaas-portal-priv:
    external: true
    name: jhaas-portal-priv
