#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$POSTGRES_DB" <<-EOSQL
	    CREATE USER "$JHAAS_DB_USER" WITH password '$JHAAS_DB_PASS';
	    CREATE DATABASE "$JHAAS_DB_NAME";
      ALTER DATABASE "$JHAAS_DB_NAME" OWNER TO "$JHAAS_DB_USER"
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$POSTGRES_DB" <<-EOSQL
	    CREATE USER "$AUTHENTIK_DB_USER" WITH password '$AUTHENTIK_DB_PASS';
	    CREATE DATABASE "$AUTHENTIK_DB_NAME";
      ALTER DATABASE "$AUTHENTIK_DB_NAME" OWNER TO "$AUTHENTIK_DB_USER"
EOSQL
